salor-retail/config/routes.rb
SalorRetail::Application.routes.draw do
  
  match "users/signup" => "users#signup"
  match "users/clockin" => "users#clockin"
  match "users/clockout" => "users#clockout"
  match "users/verify" => "users#verify"
  match 'users/destroy_login' => 'users#destroy_login'
  match 'users/login' => 'users#login'
  
  match "vendors/csv" => "vendors#csv"
  match "vendors/backup" => "vendors#backup"
  match "vendors/history" => "vendors#history"
  match "vendors/:id/display_logo" => 'vendors#display_logo'
  match "vendors/edit_field_on_child" => "vendors#edit_field_on_child"
  match "vendors/get_configuration" => "vendors#get_configuration"
  match "vendors/toggle" => "vendors#toggle"
  match "vendors/destroy/:id" => "vendors#destroy"
  match "vendors/end_day" => "vendors#end_day"
  match "vendors/end_day" => "vendors#end_day"
  match "vendors/open_cash_drawer" => "vendors#open_cash_drawer"
  match "vendors/export" => "vendors#export"
  match "vendors/clearcache" => "vendors#clearcache"
  match "vendors/export" => "vendors#export"
  match "vendors/new_drawer_transaction" => "vendors#new_drawer_transaction"
  match "vendors/labels"
  match "vendors/spy" => "vendors#spy"
  match "vendors/render_report_day" => 'vendors#render_report_day'
  match "vendors/render_open_cashdrawer" => 'vendors#render_open_cashdrawer'
  match "vendors/render_drawer_transaction_receipt" => 'vendors#render_drawer_transaction_receipt'
  match 'vendors/:id/logo' => 'vendors#logo'
  match 'vendors/:id/logo_invoice' => 'vendors#logo_invoice'
  match "vendors/report_day" => "vendors#report_day"
  match "vendors/sales_statistics" => "vendors#sales_statistics"
  
  match "buttons/position" => "buttons#position"
  
  match "categories/categories_json" => "categories#categories_json"
  match "categories/items_json" => "categories#items_json"
  
  match "orders/complete" => "orders#complete"
  match "orders/receipts" => "orders#receipts"
  match "orders/undo_drawer_transaction" => "orders#undo_drawer_transaction"
  match "orders/add_item_ajax" => "orders#add_item_ajax"
  match "orders/order_reports" => "orders#order_reports"
  match "orders/merge_into_current_order" => "orders#merge_into_current_order"
  match "orders/new_from_proforma" => "orders#new_from_proforma"
  match "orders/update_order_item" => "orders#update_order_item"
  match "orders/set_weight" => "orders#set_weight"
  match "orders/recently_tagged" => "orders#recently_tagged"
  match "orders/print_order_receipt" => "orders#print_order_receipt"
  match "orders/print_confirmed" => "orders#print_confirmed"
  match "orders/render_order_receipt" => "orders#render_order_receipt"
  match "orders/last_five_orders" => "orders#last_five_orders"
  match "orders/clear" => "orders#clear"
  match "orders/remove_payment_method" => "orders#remove_payment_method"
  match "orders/bancomat" => "orders#bancomat"
  match "orders/offline" => "orders#offline"
  match "orders/new_pos" => "orders#new_pos"
  match "orders/swap" => "orders#swap"
  match "orders/prev_order" => "orders#prev_order"
  match "orders/show_payment_ajax" => "orders#show_payment_ajax"
  match "orders/new_order" => "orders#new_order"
  match "orders/activate_gift_card" => "orders#activate_gift_card"
  match "orders/update_order_items" => "orders#update_order_items"
  match "orders/update_pos_display" => "orders#update_pos_display"
  match "orders/delete_order_item" => "orders#delete_order_item"
  match "orders/connect_loyalty_card" => "orders#connect_loyalty_card"
  match "orders/print_receipt" => "orders#print_receipt"
  match "orders/void" => "orders#void"
  match "orders/:id/print" => "orders#print"
  match "orders/print" => "orders#print"
  match "orders/log" => "orders#log"
  match "orders/:id/customer_display" => 'orders#customer_display'
  match "orders/create_all_recurring" => "orders#create_all_recurring"
  
  
  
  match "reports/index" => "reports#index"
  match "reports" => "reports#index"
  match "reports/daily" => "reports#daily"
  match "reports/cash_account" => "reports#cash_account"
  
  
  
  match "customers/labels" => "customers#labels"
  match "customers/render_label" => "customers#render_label"
  match "customers/download" => "customers#download"
  match "customers/upload_optimalsoft" => "customers#upload_optimalsoft"
  
  

  match "cash_registers/end_of_day" => "cash_registers#end_of_day"

  
  
  
  match "items/search" => "items#search"
  match "items/report" => "items#report"
  match "items/export_broken_items" => "items#export_broken_items"
  match "items/reorder_recommendation" => "items#reorder_recommendation"
  match "items/update_location" => "items#update_location"
  match "items/move_real_quantity" => "items#move_real_quantity"
  match "items/labels" => "items#labels"
  match "items/selection" => "items#selection"
  match "items/upload" => "items#upload"
  match "items/upload" => "items#upload"
  match "items/upload_house_of_smoke" => "items#upload_house_of_smoke"
  match "items/upload_danczek_tobaccoland_plattner" => "items#upload_danczek_tobaccoland_plattner"
  match "items/upload_optimalsoft" => "items#upload_optimalsoft"
  match "items/download" => "items#download"
  match "items/info" => "items#info"
  match "items/gift_cards" => "items#gift_cards"
  match "items/create_ajax" => "items#create_ajax"
  match "items/render_label" => "items#render_label"
  
  
  
  match "inventory_reports/current" => "inventory_reports#current"
  match "inventory_reports/update_real_quantity" => "inventory_reports#update_real_quantity"
  match "inventory_reports/create_inventory_report" => "inventory_reports#create_inventory_report"
  match "inventory_reports/inventory_json" => "inventory_reports#inventory_json"
  

  

  
  match "shipments/move_all_items_into_stock" => "shipments#move_all_items_into_stock"
  match "shipments/new_shipments" => "shipments#new_shipments"
  match "shipments/move_item_into_stock" => "shipments#move_item_into_stock"
  match "shipments/add_item" => "shipments#add_item"
  
  match "shippers/update_all" => "shippers#update_all"
  
  match 'translations' => 'translations#index'
  match 'translations/set' => 'translations#set'
  
  
  match "actions/create" => "actions#create"
  match "plugins/create" => "plugins#create"

  
    
#   match "api/order" => "api#order"
#   "authenticate,create,update,destroy,add_item".split(',').each do |u|
#     post "api/#{u}"
#   end
#   %Q[search,time,registers,vendors,order,order_items,locations,categories,customers,discounts,items].split(',').each do |u|
#     get "api/#{u}"
#   end

  
  
  
  
  match 'transaction_tags/:id/logo' => 'transaction_tags#logo'
  
  
  
  match 'nodes/receive' => 'nodes#receive'

  resources :inventory_reports
  resources :invoice_blurbs
  resources :payment_methods
  resources :reports
  resources :transaction_tags
  resources :buttons
  resources :broken_items
  resources :shipment_types
  resources :discounts
  resources :shippers do
    post :upload
  end
  resources :shipments
  resources :configurations
  resources :customers
  resources :cash_registers
  resources :item_types
  resources :tax_profiles
  resources :users
  resources :actions
  resources :plugins
  resources :orders
  resources :items do
    get :new_action
  end
  resources :locations
  resources :stock_locations
  resources :categories
  resources :vendors
  resources :nodes
  resources :countries
  resources :invoice_notes
  resources :sale_types
  
  resource :session do
    get :test_exception
    post :email
    get :test_email
    get :remote_service
    get :connect_remote_service
    get :update_connection_status
    get :documentation
  end

  if defined?(SrSaas::Engine) == 'constant'
    mount SrSaas::Engine => "/saas"
    match '/signin' => 'sr_saas/sessions#new'
    match '*path' => 'sr_saas/sessions#new'
    root :to => 'orders#new'
  else
    match '*path' => 'sessions#new'
    root :to => 'orders#new'
  end
end

salor-retail/app/models/shipment.rb
# coding: UTF-8

# Salor -- The innovative Point Of Sales Software for your Retail Store
# Copyright (C) 2012-2013  Red (E) Tools LTD
# 
# See license.txt for the license applying to all files within this software.

class Shipment < ActiveRecord::Base
  include SalorScope
  include SalorBase

  belongs_to :shipper, :polymorphic => true
  belongs_to :receiver, :polymorphic => true
  belongs_to :shipment_type
  has_many :notes, :as => :notable, :order => "id desc"
  has_many :shipment_items
  belongs_to :vendor
  belongs_to :company
  belongs_to :user
  
  validates_presence_of :vendor_id, :company_id

  monetize :price_cents
  monetize :total_cents
  monetize :purchase_price_total_cents

  #accepts_nested_attributes_for :notes
  #accepts_nested_attributes_for :shipment_items


  #README
  # 1. The rails way would lead to many duplications
  # 2. The rails way would require us to reorganize all the translation files
  # 3. The rails way in this case is admittedly limited, by their own docs, and they suggest you implement your own
  # 4. Therefore, don't remove this code.
  def self.human_attribute_name(attrib, options={})
    begin
      trans = I18n.t("activerecord.attributes.#{attrib.downcase}", :raise => true) 
      return trans
    rescue
      SalorBase.log_action self.class, "trans error raised for activerecord.attributes.#{attrib} with locale: #{I18n.locale}"
      return super
    end
  end
  
  def receiver_shipper_list
    ret = []
    self.vendor.shippers.visible.order(:name).each do |shipper|
      ret << {:name => shipper.name, :value => 'Shipper:' + shipper.id.to_s}
    end
    self.company.vendors.visible.all.each do |vendor|
      ret << {:name => vendor.name, :value => 'Vendor:' + vendor.id.to_s}
    end
    return ret
  end
  
  def the_receiver=(val)
    parts = val.split(':')
    self.receiver_type = parts[0]
    self.receiver_id = parts[1].to_i
    #self.save
  end
  
  def the_receiver
    return "#{self.receiver_type}:#{self.receiver_id}"
  end
  
  def the_shipper=(val)
    parts = val.split(':')
    self.shipper_type = parts[0]
    self.shipper_id = parts[1].to_i
    #self.save
  end
  
  def the_shipper
    return "#{self.shipper_type}:#{self.shipper_id}"
  end
  
  def set_notes=(notes_list)
    ids = []
    notes_list.each do |n|
      if n[:id] then
        ids << n[:id]
      else
        nnote = Note.new(n)
        nnote.save
        ids << nnote.id
      end
    end
    self.note_ids = ids
  end
  
  def set_items=(items_list)
    ids = []
    vid = self.vendor_id
    items_list.each do |li|
      ih = li[1]
      nih = {}
      ih.each do |k,v|
        nih[k.to_sym] = v
      end
      ih = nih
      next if ih[:sku].empty?
      
      if ih[:_delete].to_i == 1 then
        ih.delete(:_delete)
        next
      end
      anitem = Item.find_by_sku(ih[:sku])
      if not anitem then
        next
      end
      slocs = ih.delete(:set_stock_location_ids)
      # puts self.shipment_item_ids.inspect
      # puts ih.inspect
      if self.shipment_item_ids.include? ih[:id].to_i then
        if ShipmentItem.exists? ih[:id] then
          i = ShipmentItem.find(ih[:id])
#           raise "Existing: " + i.inspect
          i.update_attributes(ih)
          i.set_stock_location_ids = slocs
          ids << i.id
          i.save
        end
        next
      end
      ih.delete(:_delete)
      
      i = ShipmentItem.new(ih)
      i.set_stock_location_ids = slocs
      i.shipment_id = self.id
#       raise "New: " + i.inspect
      i.save
      if i then
        ids << i.id
      end
    end
    self.shipment_item_ids = ids 
    #self.save
  end

  def move_all_items_into_stock
    self.shipment_items.visible.each do |si|
      if si.in_stock_quantity == si.quantity || si.tax_profile_id.nil?
        log_action I18n.t("system.errors.shipment_item_already_in_stock", :sku => si.sku)
        next
      end
      si.move_into_stock(si.quantity - si.in_stock_quantity.to_i)
    end
  end
  
  def to_json
    attrs = {
      :id => self.id,
      :price => self.price.to_f,
      :receiver_id => self.receiver_id,
      :shipper_id => self.shipper_id,
      :shipper_type => self.shipper_type,
      :receiver_type => self.receiver_type,
      :total => self.total.to_f,
      :purchase_price_total => self.purchase_price_total.to_f,
      :name => self.name,
      :shipment_type_id => self.shipment_type_id
    }
    attrs.to_json
  end
  
  def self.shipment_items_to_json(shipment_items)
    "[#{shipment_items.collect { |si| si.to_json }.join(", ") }]"
  end
  
  def calculate_totals
    self.total_cents = self.shipment_items.visible.sum(:total_cents)
    self.purchase_price_total_cents = self.shipment_items.visible.sum(:purchase_price_total_cents)
    self.save
  end
  
  def add_shipment_item(params)
    return nil if params[:sku].blank?
    # get existing regular item
    si = self.shipment_items.visible.where(:sku => params[:sku]).first
    if si then
      log_action "Item is normal, and present, just increment"
      si.quantity += 1 
      si.calculate_totals
      si.save
      self.calculate_totals
      return si
    else
      log_action "ShipmentItem not found on Shipment. Will not increment."
    end
    

    # finally create the item
    si = ShipmentItem.new
    si.vendor = self.vendor
    si.company = self.company
    si.shipment = self
    si.quantity = 1
    si.sku = params[:sku]
    si.currency = self.vendor.currency
    
    # try to get default data from existing Items
    item = self.vendor.items.visible.find_by_sku(params[:sku])
    if item
      si.price_cents = item.price_cents
      si.purchase_price_cents = item.purchase_price_cents
      si.name = item.name
      si.tax_profile = item.tax_profile
    else
      # defaults
      si.price_cents = 0
      si.purchase_price_cents = 0
      si.name = "?"
    end
 
    si.calculate_totals
    self.shipment_items << si
    self.calculate_totals
    return si
  end
end

salor-retail/app/models/shipment_type.rb
# coding: UTF-8

# Salor -- The innovative Point Of Sales Software for your Retail Store
# Copyright (C) 2012-2013  Red (E) Tools LTD
# 
# See license.txt for the license applying to all files within this software.

class ShipmentType < ActiveRecord::Base
  include SalorBase
  include SalorScope

  has_many :shipments
  belongs_to :vendor
  belongs_to :company
  
  validates_presence_of :name
  validates_presence_of :vendor_id, :company_id
end

salor-retail/app/controllers/shipments_controller.rb
# coding: UTF-8

# Salor -- The innovative Point Of Sales Software for your Retail Store
# Copyright (C) 2012-2013  Red (E) Tools LTD
# 
# See license.txt for the license applying to all files within this software.
class ShipmentsController < ApplicationController

  before_filter :check_role, :except => [:move_all_to_items, :move_shipment_item]

  
  def index
  @shipments = @current_vendor.shipments.visible.page(params[:page]).per(@current_vendor.pagination).order('created_at desc')
  end

  def show
    @shipment = @current_vendor.shipments.visible.find_by_id(params[:id])
  end

  def new
    @shipment = Shipment.new
    @shipment.vendor = @current_vendor
    @shipment.company = @current_company
    @shipment.receiver_id = @current_vendor.id
    @shipment.receiver_type = 'Vendor'
    @shipment_types = @current_vendor.shipment_types.visible.order(:name)
    @shipment_items = []
  end

  def edit
    @shipment = @current_vendor.shipments.visible.find_by_id(params[:id])
    @shipment_items = @shipment.shipment_items.visible
    @shipment_types = @current_vendor.shipment_types.visible.order(:name)
  end

  def create
    @shipment = Shipment.new(params[:shipment])
    @shipment.vendor = @current_vendor
    @shipment.company = @current_company
    @shipment.currency = @current_vendor.currency
    @shipment.total_cents = 0
    @shipment.purchase_price_total_cents = 0
    if @shipment.save
      @shipment.shipment_items.update_all :vendor_id => @shipment.vendor_id,
          :company_id => @shipment.company_id,
          :currency => @current_vendor.currency
      @shipment_items = @shipment.shipment_items.visible
      redirect_to edit_shipment_path(@shipment)
    else
      @shipment_types = @current_vendor.shipment_types.visible.order(:name)
      @shipment_items = @shipment.shipment_items.visible
      render :new
    end
  end

  def update
    @shipment = @current_vendor.shipments.visible.find_by_id(params[:id])
    if @shipment.update_attributes(params[:shipment])
      @shipment.shipment_items.update_all :vendor_id => @shipment.vendor_id, :company_id => @shipment.company_id
      redirect_to edit_shipment_path(@shipment)
    else
      @shipment_types = @current_vendor.shipment_types.visible.order(:name)
      render :edit
    end
  end

  def destroy
    @shipment = @current_vendor.shipments.visible.find_by_id(params[:id])
    @shipment.hide(@current_user)
    redirect_to shipments_path
  end
  
  #ajax
  def add_item
    @shipment = @current_vendor.shipments.visible.find_by_id(params[:shipment_id])
    @shipment_item = @shipment.add_shipment_item(params)
    @shipment_items = []
    
    @shipment_items << @shipment_item
    render :update_pos_display
  end
  
  #ajax
  def move_all_items_into_stock
    @shipment = @current_vendor.shipments.visible.find_by_id(params[:shipment_id])
    @shipment.move_all_items_into_stock
    render :nothing => true
  end
  
  #ajax
  def move_item_into_stock
    @shipment_item = @current_vendor.shipment_items.visible.find_by_id(params[:shipment_item_id])
    @shipment_item.move_into_stock(params[:quantity], params[:locationstring])
    render :nothing => true
  end
end

salor-retail/app/views/shipments/_form2.html.erb
<div align="center">


  <%= form_for(@shipment, :html => {:id => 'shipments_form'}) do |f| %>
    <% if @shipment.errors.any? %>
      <div id="error_explanation">
        <h2><%= I18n.t("activerecord.errors.template.header", :count => @shipment.errors.count,:model => Shipment.model_name.human)%></h2>

        <ul>
        <% @shipment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    
    <table width="100%" align="center">
      <tr>
        <td align="left">
          <div class="button-confirm"><%= link_to(t('helpers.submit.cancel'), shipments_path) %></div>
          <% unless @shipment.new_record? %>
          <div class="button-confirm"><%= link_to(t('shipments.index.report'), shipment_path(@shipment)) %></div>
          <% end %>
        </td>
        <td align="right">
          <div class="actions"><%= f.submit(t('helpers.submit.save'), :id => "submit") %></div>
        </td>
      </tr>
      <tr>
        <td valign="top">  
          <h2><%= t("menu.general_configuration") %></h2>
        </td>
        <td>
          <hr />
        </td>
      </tr>
      <tr>
        <td> <%= f.label t("activerecord.attributes.name") %> </td>
        <td> <%= f.text_field :name, :class => "keyboardable"%> </td>
      </tr>
      <tr>
        <td> <%= f.label t("activerecord.attributes.paid") %> </td>
        <td> <%= f.check_box :paid %> </td>
      </tr>
      
      <tr>
        <td> <%= f.label t("activerecord.attributes.status") %> </td>
        <td> <%= f.collection_select :shipment_type_id, @shipment_types, :id, :name, :include_blank => true %> </td>
      </tr>
      
      <tr>
        <td> <%= f.label t("activerecord.attributes.the_receiver") %> </td>
        <td> <%= f.select :the_receiver, @shipment.receiver_shipper_list.collect{|t| [t[:name],t[:value]]} %> </td>
      </tr>
      
      <tr>
        <td> <%= f.label t("activerecord.attributes.the_shipper") %> </td>
        <td> <%= f.select :the_shipper, @shipment.receiver_shipper_list.collect {|t| [t[:name],t[:value]]}.unshift(['', '']) %> </td>
      </tr>
      
      <tr>
        <td valign="top">  
          <h2><%= t("menu.items") %></h2>
        </td>
        <td>
          <hr />
        </td>
      </tr>
    </table>
  <% end %>

  <% unless @shipment.new_record? %>
  <%= render :partial => "shipment_item_form" %>
  <% end %>



</div>

salor-retail/app/views/shipments/_shipment_item_form.html.haml
:javascript
  $(function() {
    sr.data.shipments.shipment_items = #{ raw Shipment.shipment_items_to_json(@shipment_items) };
    sr.data.shipments.shipment = #{ raw @shipment.to_json };
    sr.fn.shipments.updateLineItems();
    sr.fn.shipments.updateShipment();

    $('#main_shipment_sku_field').keydown(function(e) {
      if (e.which == 13) {
        sr.fn.shipments.submitLineItem($('#main_shipment_sku_field').val());
        $('#main_shipment_sku_field').val('');
        return false;
      }
    });
  sr.fn.onscreen_keyboard.make($('#main_shipment_sku_field'));

  });

#pos_order_total.pos-order-total
%input#main_shipment_sku_field

  
  
#shipment_items_container

salor-retail/app/views/shipments/edit.html.erb
<%= raw content_box_top(I18n.t("menu.shipments")) %>
<%= render 'form2' %>

salor-retail/app/views/shipments/index.html.haml
= raw content_box_top(I18n.t("headings.shipments"))
  
%div.pagination= paginate @shipments if @shipments


%table{:width=>"90%",:align=>"center", :class => 'stripe-me'}
  %tr{:class => 'no-stripe'}
    %td{:colspan=>9,:align=>'right'}
      = link_to (t 'menu.new_shipment'), new_shipment_path, :class => 'links new-model-button'
  %tr{:class => 'no-stripe'}
    %td{:colspan=>9}
      %h2= t('activerecord.models.shipment.other')
      %hr
  %tr
    %th= Shipment.human_attribute_name(:name).upcase
    %th= Shipment.human_attribute_name(:from).upcase
    %th= Shipment.human_attribute_name(:to).upcase
    %th= Shipment.human_attribute_name(:price).upcase
    %th= Shipment.human_attribute_name(:paid).upcase
    %th= Shipment.human_attribute_name(:status).upcase
    %th
    %th
   
  - @shipments.each do |s|
    - sname = s.shipper.nil? ? t("system.errors.value_not_set") : s.shipper.name
    - rname = s.receiver.nil? ? t("system.errors.value_not_set") : s.receiver.name
    %tr
      %td= link_to s.name, shipment_path(s)
      %td= sname
      %td= rname
      %td= humanized_money_with_symbol(s.purchase_price_total)
      %td= s.paid
      %td= s.shipment_type.name if s.shipment_type
      %td{:align=>:center}= link_to salor_icon(:edit,{},32,t(:edit)), edit_shipment_path(s)
      %td{:align=>:center}= link_to salor_icon(:delete,{},32,t("menu.destroy")), shipment_path(s), :method => :delete, :confirm => t(:are_you_sure)

salor-retail/app/views/shipments/new.html.erb
<%= raw content_box_top(I18n.t("menu.new_shipment")) %>
<%= render 'form2' %>

salor-retail/app/views/shipments/show.html.haml
= stylesheet_link_tag 'invoice_default'
= stylesheet_link_tag 'invoice_default_print', :media => 'print'

= raw content_box_top(@shipment.name)

.tools
  .tool-icon{ :onmousedown => 'sr.fn.salor_bin.showPrintDialog()' }= salor_icon(:print, {}, 32)
  .tool-icon{ :onmousedown => "window.location = '/shipments/#{ @shipment.id }/edit'" }
    = salor_icon(:edit, {}, 32)
  

.clear

.paper-invoice  
  %h2== #{ Shipment.model_name.human } #{ @shipment.name }
  .right
    %p
      %b== #{ I18n.t("views.single_words.to") }:
      = l @shipment.created_at, :format => :date_short
    %p
      %b== #{ I18n.t("activerecord.attributes.price") }:
      = humanized_money_with_symbol @shipment.purchase_price_total
    %p
      %b== #{ I18n.t("activerecord.attributes.status") }:
      = @shipment.shipment_type.name if @shipment.shipment_type
    %p
      %b== #{ I18n.t("views.single_words.from") }:
      = @shipment.shipper.name if @shipment.shipper
    %p
      %b== #{ I18n.t("views.single_words.to") }:
      = @shipment.receiver.name if @shipment.receiver
  
    
  - if @shipment.notes.any?
    %h2= I18n.t("headings.notes")
    - @shipment.notes.each do |note|
      .note{ :id =>"note-#{ note.id }" }
        %span.note-title= note.title
        %br
        %p.note-body= note.body


  %h3= I18n.t("headings.shipment_items")
  %table.striped-table2
    %tr
      %th= ShipmentItem.human_attribute_name(:name)
      %th= ShipmentItem.human_attribute_name(:sku)
      %th= Item.human_attribute_name(:purchase_price)
      %th= Item.human_attribute_name(:tax_profile_id)
      %th= ShipmentItem.human_attribute_name(:quantity)
      %th= t('.purchase_price_sum')
    - @shipment.shipment_items.visible.reverse.each do |si|
      %tr
        %td= si.name
        %td= si.sku
        %td.right= humanized_money_with_symbol si.purchase_price
        %td.right= si.tax_profile.name if si.tax_profile
        %td.center= si.quantity
        %td.right= humanized_money_with_symbol si.purchase_price_total if si.purchase_price_total
    %tr.total
      %td{ :colspan => 5 }
      %td.right= humanized_money_with_symbol @shipment.purchase_price_total
      
.paper-invoice
  %p
    .dialog-button{ :onclick => "sr.fn.shipments.moveAllItemsIntoStock(#{ @shipment.id });" }= t('menu.move_shipment_item')
  %table.striped-table2
    %tr
      %th= ShipmentItem.human_attribute_name(:name)
      %th= ShipmentItem.human_attribute_name(:sku)
      %th= ShipmentItem.human_attribute_name(:quantity)
      %th
      %th
    - @shipment.shipment_items.visible.reverse.each do |si|
      - item = @shipment.vendor.items.visible.find_by_sku(si.sku)
      - item_stocks = item.item_stocks.visible if item
      - item_stocks ||= []
      %tr
        %td= si.name
        %td= si.sku
        %td= si.quantity
        %td
          - if si.in_stock_quantity == si.quantity
            = t ('views.forms.shipment.types.in_stock')
          - elsif item.nil? and si.tax_profile.nil?
            = t ('.need_tax_profile')
          - else
          
            = text_field_tag "shipment_item_quantity_to_move_#{ si.id }", (si.quantity - si.in_stock_quantity.to_f), :class => 'shipment_item_quantity_to_move', :onclick => "$(this).select()"
            
            - unless item.blank? or item_stocks.blank?
              = select_tag "shipment_item_move_to_#{ si.id }", options_for_select(@shipment.vendor.location_stock_location_list), :class => 'shipment_item_move_to' , :include_blank => true, :onchange => "$('#shipment_item_move_button_#{ si.id }').fadeIn();"
              
              .dialog-button{ :id => "shipment_item_move_button_#{ si.id }", :style => "display:none;", :onclick => "sr.fn.shipments.move_item_into_stock(#{ si.id }, $('#shipment_item_quantity_to_move_#{ si.id }').val(), $('#shipment_item_move_to_#{ si.id }').val() );" }= t('.move_into_stock')
              
            - else
            
              .dialog-button{ :id => "shipment_item_move_button_#{ si.id }", :onclick => "sr.fn.shipments.move_item_into_stock(#{ si.id }, $('#shipment_item_quantity_to_move_#{ si.id }').val() );" }= t('.move_into_stock')
        %td
          - if item
            - if item_stocks.blank?
              %table
                %tr
                  %th= t 'views.locations'
                  %th= t 'views.quantity'
                %tr
                  %td= item.location.name if item.location
                  %td= item.quantity
            - else
              %table
                %tr
                  %th= t 'views.locations'
                  %th= t 'views.quantity'
                - item_stocks.each do |is|
                  %tr
                    %td= is.location.name if is.location
                    %td= is.quantity

salor-retail/app/views/shipments/update_pos_display.js.erb
// README: This view only takes a single instance of @shipment, and an Array @shipment_items. The controllers are responsible for supplying those variables to keep this view simple.

// ---------- update order -------------
sr.data.shipments.shipment = <%= raw @shipment.to_json %>;
try {
  sr.fn.shipments.updateShipment();
} catch (err) {
  sr.fn.debug.sendEmail("Error in update_pos_display updateShipment", err);
}


// ----------- update order items ----------
sr.data.shipments.shipment_items = <%= raw Shipment.shipment_items_to_json(@shipment_items) %>;
try {
  sr.fn.shipments.updateLineItems(); 
} catch (err) {
  sr.fn.debug.echo("Failed to update items properly, please reload");
  sr.fn.debug.echo(err);
  sr.fn.debug.sendEmail("Error in update_pos_display updateLineItems", err);
}

// ---------- other stuff ----------
sr.fn.focus.set($('#main_sku_field'));